# Generated by Django 5.0.7 on 2024-08-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='shop/images/default.jpg', upload_to='shop/images'),
        ),
    ]
