# Generated by Django 5.0.7 on 2024-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
