# Generated by Django 5.0.7 on 2024-08-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cartitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ph_no', models.IntegerField(max_length=15, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
