# Generated by Django 5.0.7 on 2024-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_contact_ph_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('ph_no', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
